wandb_version: 1

epsilon:
  desc: null
  value: 0.1
batch_size:
  desc: null
  value: 1
normalization_bounds:
  desc: null
  value:
  - 0
  - 1
cost_samples:
  desc: null
  value: 1000
h_ind:
  desc: null
  value:
  - - 0
    - 1
  - - 2
    - 3
    - 4
  - - 5
    - 6
obj_funcs:
  desc: null
  value:
  - levy2
  - ackley3
  - rosenbrock2
cost_types:
  desc: null
  value:
  - 2
  - 1
  - 3
decay_factor:
  desc: null
  value: 0.2
warmup_eta:
  desc: null
  value: 0.01
n_trials:
  desc: null
  value: 10
n_iters:
  desc: null
  value: 50
n_init_data:
  desc: null
  value: 10
prefix_thresh:
  desc: null
  value: 10000000
warmup_iters:
  desc: null
  value: 10
use_pref_pool:
  desc: null
  value: 1
verbose:
  desc: null
  value: 1
rand_seed:
  desc: null
  value: 42
acqf:
  desc: null
  value: EI
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683315012.426938
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.10
      5: 0.15.1
      8:
      - 5
